include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  errors:
    public_member_api_docs: ignore 
    lines_longer_than_80_chars: ignore
    inference_failure_on_function_invocation: ignore 
    always_put_required_named_parameters_first: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
