name: code_con
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dart_frog: ^1.1.0
  dio: ^5.7.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  shelf_cors_headers: ^0.1.5

dev_dependencies:
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^5.1.0
